<a href="https://colab.research.google.com/github/jr2950499/Numpy/blob/main/Numpy_%EC%8B%A4%EC%8A%B5_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#실습 1-3 shape, 인덱스, reshape, zeros, ones
shape, 인덱스, reshape, zeros, ones

In [ ]:
import numpy as np

In [ ]:
arr = np.array ([[1,2,3],[4,5,6]])

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.ndim

2

In [ ]:
arr.size

6

In [ ]:
len(arr)

2

In [ ]:
arr[1,0]

4

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[1,2]

6

In [ ]:
arr[0,2]

3

In [ ]:
#넘파이 객체로부터 직접호출

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.shape

(2, 3)

In [ ]:
np.shape(arr)

(2, 3)

In [ ]:
#행과 열만 구하기

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.shape[0]  #행만

2

In [ ]:
arr.shape[1]  #열만

3

In [ ]:
#reshape 구조변경

In [ ]:
arr = np.array ([[1,2,3,4,5,6],[1,2,3,4,5,6]])

In [ ]:
arr.shape

(2, 6)

In [ ]:
arr.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6]])

In [ ]:
k = arr.reshape(3,4)

In [ ]:
k

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6]])

In [ ]:
arr = np.array ([[1,2,3,4,5,6],[1,2,3,4,5,6]]).reshape(3,4)

In [ ]:
arr

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
#모든요소를 0으로

In [ ]:
arr = np.zeros((2,2))

In [ ]:
arr

array([[0., 0.],
       [0., 0.]])

In [ ]:
#모든요소를 1로

In [ ]:
arr=np.ones((2,2))

In [ ]:
arr

array([[1., 1.],
       [1., 1.]])

#실습 1-4 단위행렬
단위행렬

In [ ]:
#2차 단위행렬  #이와 같게 1차, 3차 ....

In [ ]:
arr =np.eye(2)

In [ ]:
arr

array([[1., 0.],
       [0., 1.]])

In [ ]:
#단위행렬의 성질
#E 라고 표기
#어떤행렬 A와 단위행렬 E를 곱하면 자기자신이 나옴A
#차원이 같음

#실습 1-5 arrange 로 원하는 숫자범위 간격지정

arrange 로 원하는 숫자범위 간격지정

In [ ]:
import numpy as np

In [ ]:
ar = np.arange(10)

In [ ]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(ar)

numpy.ndarray

In [ ]:
ar1 = np.arange(20)

In [ ]:
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
ar=np.arange(0,10)

In [ ]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar =np.arange(0,10,3)

In [ ]:
ar

array([0, 3, 6, 9])

In [ ]:
ar=np.arange(1,20,2)

In [ ]:
ar

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
ar= np.arange(0,21,2)   #20까지 출력 원하면 21 까지 써야함

In [ ]:
ar=np.arange(1,10)

In [ ]:
ar=np.arange(1,10,.5)

In [ ]:
ar

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
ar =np.arange(1,20,.2)

In [ ]:
ar

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
#arange, reshape
#3x3 행렬을 수동으로만들면

In [ ]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
ar.shape

(3, 3)

In [ ]:
ar_new = np.arange(9)

In [ ]:
ar_new

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
ar_new.ndim

1

In [ ]:
ar_new.shape

(9,)

In [ ]:
ar_new = ar_new.reshape(3,3)

In [ ]:
ar_new

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
ar_new

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
ar_new.size

9

In [ ]:
ar.size

9

In [ ]:
ar_test = np.arange(1,10)

In [ ]:
ar_test

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar_test = ar_test.reshape(3,3)

In [ ]:
ar_test

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.arange(1,10).reshape(3,3)

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#6X6

In [ ]:
arr =np.arange(1,37)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [ ]:
arr=arr.reshape(6,6)

In [ ]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [ ]:
arr = np.arange(100).reshape(10,10)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
arr.shape

(10, 10)

In [ ]:
arr.size

100

In [ ]:
arr[0,9]

9

In [ ]:
arr[4,7]

47

In [ ]:
len(arr[4])

10

In [ ]:
arr[4].size

10

In [ ]:
ar = np.arange(12).reshape(3,4)

In [ ]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
ar.ndim

2

In [ ]:
ar.size

12

In [ ]:
len(ar)

3

In [ ]:
len(ar[2])

4

#실습 1-6 넘파이 (-1) shape 열,행 기준
넘파이 (-1) shape 열,행 기준


In [ ]:
#열 기준

In [ ]:
#reshape(-1,n)  #일렬로 배열

In [ ]:
ar = np.arange(12).reshape(3,4)

In [ ]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
ar1= ar.reshape(-1,1)  #=(12,1)

In [ ]:
ar1

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [ ]:
ar = np.arange(1,20,.5)

In [ ]:
ar

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5])

In [ ]:
ar.size

38

In [ ]:
ar = ar.reshape(-1,1)  #(38,1)

In [ ]:
ar

array([[ 1. ],
       [ 1.5],
       [ 2. ],
       [ 2.5],
       [ 3. ],
       [ 3.5],
       [ 4. ],
       [ 4.5],
       [ 5. ],
       [ 5.5],
       [ 6. ],
       [ 6.5],
       [ 7. ],
       [ 7.5],
       [ 8. ],
       [ 8.5],
       [ 9. ],
       [ 9.5],
       [10. ],
       [10.5],
       [11. ],
       [11.5],
       [12. ],
       [12.5],
       [13. ],
       [13.5],
       [14. ],
       [14.5],
       [15. ],
       [15.5],
       [16. ],
       [16.5],
       [17. ],
       [17.5],
       [18. ],
       [18.5],
       [19. ],
       [19.5]])

In [ ]:
ar1= ar.reshape (-1,2)

In [ ]:
ar1

array([[ 1. ,  1.5],
       [ 2. ,  2.5],
       [ 3. ,  3.5],
       [ 4. ,  4.5],
       [ 5. ,  5.5],
       [ 6. ,  6.5],
       [ 7. ,  7.5],
       [ 8. ,  8.5],
       [ 9. ,  9.5],
       [10. , 10.5],
       [11. , 11.5],
       [12. , 12.5],
       [13. , 13.5],
       [14. , 14.5],
       [15. , 15.5],
       [16. , 16.5],
       [17. , 17.5],
       [18. , 18.5],
       [19. , 19.5]])

In [ ]:
ar2 = ar.reshape(-1,3)

ValueError: cannot reshape array of size 38 into shape (3)

In [ ]:
ar= np.arange(1,20,.5)

In [ ]:
ar

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5])

In [ ]:
ar=np.arange(39)

In [ ]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38])

In [ ]:
ar=ar.reshape(-1,3)

In [ ]:
ar

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38]])

In [ ]:
ar = np.arange(12).reshape(3,4)

In [ ]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
ar = ar.reshape(-1,3)

In [ ]:
ar

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
ar2 = ar.reshape(-1,6) #(2,6)

In [ ]:
ar2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
#행 기준

In [ ]:
ar = np.arange(12)

In [ ]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
ar = ar.reshape(1,-1)

In [ ]:
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [ ]:
ar2 = ar.reshape(2,-1)

In [ ]:
ar2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
ar3 = ar.reshape(3,-1)

In [ ]:
ar3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#reshape(-1)

In [ ]:
ar = np.arange(12).reshape(3,4)

In [ ]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
ar1 = ar.reshape(-1) #(1,-1)  (1,12)  세개 같은거다!!!!!!!!!!!!!!!!!!!!!!!!!

In [ ]:
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
ar_test = ar.reshape(-1,1)

In [ ]:
ar_test

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [ ]:
ar_test = ar.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [ ]:
ar_test = ar.reshape(2,-45)  #- 자체에 값을 무시하는 경향이 있다.

In [ ]:
ar_test

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
ar_test2 = ar.reshape(3,-99)

In [ ]:
ar_test2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#실습 1-7 넘파이 자료형

datatype int float dtype astype bool

In [ ]:
#넘파이 데이터 타입

In [ ]:
ar1 = np.array ([1,2,3.5,4,5])

In [ ]:
ar1

array([1. , 2. , 3.5, 4. , 5. ])

In [ ]:
type(ar1)

numpy.ndarray

In [ ]:
ar1.dtype

dtype('float64')

In [ ]:
ar2 = np.array([1,2,3,4,5])

In [ ]:
ar2

array([1, 2, 3, 4, 5])

In [ ]:
ar2.dtype

dtype('int64')

In [ ]:
type(ar2)

numpy.ndarray

In [ ]:
ar2 = np.array([1,2,3,4,5],dtype=np.uint8)  #데이터 타입을 지정해줄수있다

In [ ]:
ar2

array([1, 2, 3, 4, 5], dtype=uint8)

In [ ]:
ar3 = np.arange(10, dtype=np.int64)

In [ ]:
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#기존 array->새로운 타입으로 변환

In [ ]:
ar1 = np.array([1,2,3,4,5])

In [ ]:
ar1

array([1, 2, 3, 4, 5])

In [ ]:
ar1.dtype

dtype('int64')

In [ ]:
ar2 = np.astype(np.float64)

AttributeError: module 'numpy' has no attribute 'astype'

In [ ]:
ar2 = ar1.astype(np.float64)   #astype 앞에는 원본적기!!!!!!!!!!!!!!! 헷갈림주의

In [ ]:
ar2

array([1., 2., 3., 4., 5.])

In [ ]:
#bool

In [ ]:
ar1 = np.array([True,False])

In [ ]:
ar1

array([ True, False])

In [ ]:
print(ar1)

[ True False]


In [ ]:
ar1.dtype

dtype('bool')

#실습 1-8 int_float_str/ 빅엔디언 리틀엔디언/ issubdtype 자료형확인

In [ ]:
#int vs int_
#int_ 32, 64 float_ 64를 가르키는거임

In [ ]:
a=np.int_([1,2,3,4,5])

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b=np.int([1,2,3,4,5])

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [ ]:
b =int(190)

In [ ]:
b

190

In [ ]:
type(b)

int

In [ ]:
b.dtype

AttributeError: 'int' object has no attribute 'dtype'

In [ ]:
#float_

In [ ]:
x = np.float_(4)

In [ ]:
x

4.0

In [ ]:
x.dtype

dtype('float64')

In [ ]:
#float32 로 지정

In [ ]:
x = np.float32(99)

In [ ]:
x

99.0

In [ ]:
x.dtype

dtype('float32')

In [ ]:
#float_ 배열 생성

In [ ]:
ar = np.float_([1,2,3,4,5])

In [ ]:
ar

array([1., 2., 3., 4., 5.])

In [ ]:
ar.dtype

dtype('float64')

In [ ]:
ar=np.float32([1,2,3,4,5])

In [ ]:
ar

array([1., 2., 3., 4., 5.], dtype=float32)

In [ ]:
ar = np.array([1, 2, 3, 4, 5], dtype=np.float32)

In [ ]:
ar

array([1., 2., 3., 4., 5.], dtype=float32)

In [ ]:
ar=np.float_([1,2,3,4,5],dtype = np.float32)  #이거 왜 안됨 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

TypeError: float() argument must be a string or a real number, not 'list'

In [ ]:
ar.dtype

dtype('float32')

In [ ]:
ar

array([1., 2., 3., 4., 5.], dtype=float32)

In [ ]:
#타입 지정

In [ ]:
ar1=np.arange(10, dtype=np.uint8)

In [ ]:
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [ ]:
ar1.dtype

dtype('uint8')

In [ ]:
ar2 = np.arange(10,dtype="uint8")

In [ ]:
ar2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [ ]:
ar2.dtype

dtype('uint8')

In [ ]:
ar3 = np.arange(10,dtype='u')

TypeError: data type 'u' not understood

In [ ]:
ar3 = np.arange(10,dtype='u8') #uint8

In [ ]:
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint64)

In [ ]:
ar3=np.arange(10,dtype='u1')  #1->8비트 곱하기 8 해야함

In [ ]:
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [ ]:
ar4 =np.arange(10,dtype='u4')

In [ ]:
ar4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint32)

In [ ]:
ar3 = np.arange(10,dtype ='<u1') #uint8  < 이거는 에러 안남

In [ ]:
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [ ]:
ar3 = np.arange(10,dtype ='^u1')

TypeError: data type '^u1' not understood

In [ ]:
#자료형 확인 - issubdtype

In [ ]:
ar = np.arange(10,dtype=np.uint32)

In [ ]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint32)

In [ ]:
ar1 = ar.astype(np.float64)

In [ ]:
ar1.dtype

dtype('float64')

In [ ]:
ar.dtype

dtype('uint32')

In [ ]:
ar1.dtype

dtype('float64')

In [ ]:
np.issubdtype(ar.dtype,np.integer)  #ar.dtype 이 뒤에 integer인가?

True

In [ ]:
np.issubdtype(ar.dtype, np.float)

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [ ]:
np.issubdtype(ar.dtype,np.floating)

False

In [ ]:
ar1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.issubdtype(ar1.dtype, np.floating)

True

In [ ]:
np.issubdtype(ar1.dtype, np.float32)

False

In [ ]:
np.issubdtype(ar1.dtype, np.float64)

True

In [ ]:
#int float 자료형 변환

In [ ]:
ar = np.arange(10,dtype=np.uint8)

In [ ]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [ ]:
ar1 = ar.astype(int)

In [ ]:
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar1.dtype

dtype('int64')

In [ ]:
ar.dtype

dtype('uint8')

In [ ]:
ar2 = ar.astype(float)    #int float 으로 변환

In [ ]:
ar2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
ar2.dtype

dtype('float64')