<a href="https://colab.research.google.com/github/jr2950499/Numpy/blob/main/Numpy_%EC%8B%A4%EC%8A%B5_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#실습 3-1 판다스 설치

In [ ]:
#series, DataFrame(1차원, 2차원)

In [ ]:
import pandas as pd

#실습 3-2 Series

In [ ]:
#대소문자 주의

In [ ]:
ar = pd.Series([1,2,3,-4,5])

In [ ]:
ar

0    1
1    2
2    3
3   -4
4    5
dtype: int64

In [ ]:
type(ar)

pandas.core.series.Series

In [ ]:
#다양한 인자 입력

In [ ]:
ar1 = pd.Series([1,2,3,-4,5]) #python list

In [ ]:
ar1

0    1
1    2
2    3
3   -4
4    5
dtype: int64

In [ ]:
ar2 = pd.Series(np.array([1,2,3,-4,5]))

In [ ]:
ar2

0    1
1    2
2    3
3   -4
4    5
dtype: int64

In [ ]:
type(ar2)

pandas.core.series.Series

In [ ]:
#인덱스와 그 밸류값들이 동시에 확인 가능하다

In [ ]:
ar2 = np.arange(10)

In [ ]:
ar2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar1.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
ar.values

array([ 1,  2,  3, -4,  5])

In [ ]:
#typecheck

In [ ]:
ar1.dtype

dtype('int64')

In [ ]:
ar1.dtypes   #넘파이는 사용불가

dtype('int64')

In [ ]:
ar

0    1
1    2
2    3
3   -4
4    5
dtype: int64

In [ ]:
ar=pd.Series([1,2,3,-4,5], index=['a','b','c','d','e'])

In [ ]:
ar

a    1
b    2
c    3
d   -4
e    5
dtype: int64

In [ ]:
ar.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
ar.values

array([ 1,  2,  3, -4,  5])

In [ ]:
ar['d']

-4

In [ ]:
#파이썬 딕셔너리로 인덱스 지정

In [ ]:
pydic = {"서울":100, "부산":200, "광주":300, "세종":400}

In [ ]:
pydic

{'서울': 100, '부산': 200, '광주': 300, '세종': 400}

In [ ]:
type(pydic)

dict

In [ ]:
ar=pd.Series(pydic)

In [ ]:
ar

서울    100
부산    200
광주    300
세종    400
dtype: int64

In [ ]:
ar.index

Index(['서울', '부산', '광주', '세종'], dtype='object')

In [ ]:
ar.values

array([100, 200, 300, 400])

In [ ]:
ar['세종']

400

In [ ]:
#시리즈 이름 지정

In [ ]:
ar

서울    100
부산    200
광주    300
세종    400
dtype: int64

In [ ]:
ar.name = '대한민국 광역시'

In [ ]:
ar

서울    100
부산    200
광주    300
세종    400
Name: 대한민국 광역시, dtype: int64

In [ ]:
#index 수정

In [ ]:
ar

서울    100
부산    200
광주    300
세종    400
Name: 대한민국 광역시, dtype: int64

In [ ]:
ar.index

Index(['서울', '부산', '광주', '세종'], dtype='object')

In [ ]:
ar.index = ['a','b','c','d']

In [ ]:
ar

a    100
b    200
c    300
d    400
Name: 대한민국 광역시, dtype: int64

In [ ]:
ar.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
ar.index = [1,2,3,4]

In [ ]:
ar

1    100
2    200
3    300
4    400
Name: 대한민국 광역시, dtype: int64

In [ ]:
_ix=['a','b','c','d']

In [ ]:
ar.index=_ix

In [ ]:
ar

a    100
b    200
c    300
d    400
Name: 대한민국 광역시, dtype: int64

In [ ]:
#인덱스를 이용한 접근

In [ ]:
ar

a    100
b    200
c    300
d    400
Name: 대한민국 광역시, dtype: int64

In [ ]:
ar['a']

100

In [ ]:
ar['c']

300

In [ ]:
ar[0]

100

In [ ]:
ar[-1]

400

In [ ]:
ar[1:3]

b    200
c    300
Name: 대한민국 광역시, dtype: int64

In [ ]:
ar[2:]

c    300
d    400
Name: 대한민국 광역시, dtype: int64

In [ ]:
ar[:]

a    100
b    200
c    300
d    400
Name: 대한민국 광역시, dtype: int64

In [ ]:
#조건을 이용한 접근, 값으로 바꿈

In [ ]:
ar=pd.Series(['a','b','c','d','e'])

In [ ]:
ar

0    a
1    b
2    c
3    d
4    e
dtype: object

In [ ]:
ar[3]

'd'

In [ ]:
#a 이상만 출력하고싶다면

In [ ]:
ar[ar> 'a' ]

1    b
2    c
3    d
4    e
dtype: object

In [ ]:
ar

0    a
1    b
2    c
3    d
4    e
dtype: object

In [ ]:
ar[ar>'b']

2    c
3    d
4    e
dtype: object

In [ ]:
ar[ar>'3']

0    a
1    b
2    c
3    d
4    e
dtype: object

In [ ]:
ar=pd.Series([1,2,3,4,5])

In [ ]:
ar

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
ar[4]

5

In [ ]:
ar[ar>1] #값이라고 생각하자 이럴경우에는

1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
ar[ar>'1']

TypeError: Invalid comparison between dtype=int64 and str

In [ ]:
ar [ar!=3]

0    1
1    2
3    4
4    5
dtype: int64

In [ ]:
#Series 연산

In [ ]:
ar*2

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [ ]:
ar1 = ar*2

In [ ]:
ar2= ar**2

In [ ]:
ar2

0     1
1     4
2     9
3    16
4    25
dtype: int64

In [ ]:
#NaN

In [ ]:
#추가 인덱스 지정시 없으면 NaN

In [ ]:
a = {'강감찬':180, '이순신':185}

In [ ]:
a

{'강감찬': 180, '이순신': 185}

In [ ]:
#인덱스 추가

In [ ]:
_ix_name= ['강감찬','이순신']

In [ ]:
ar1 = pd.Series(a, index = _ix_name)

In [ ]:
ar1

강감찬    180
이순신    185
dtype: int64

In [ ]:
_ix_name= ['강감찬','이순신','홍길동']

In [ ]:
ar2 = pd.Series(a,index = _ix_name)

In [ ]:
ar2

강감찬    180.0
이순신    185.0
홍길동      NaN
dtype: float64

#실습 3-3 Dataframe 생성, 대소문자, 인덱스지정,type,ndim,size,shape,색인, 열기준처리..

In [ ]:
import pandas as pd

In [ ]:
#기본 데이터 프레임 새성

In [ ]:
df = pd.DataFrame([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
df

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [ ]:
#데이터 프레임 생성시 인덱스 지정

In [ ]:
df1= pd.DataFrame([[1,2,3,4,5],[6,7,8,9,10]], index=['a','b'])

In [ ]:
df1

0  1  2  3   4
a  1  2  3  4   5
b  6  7  8  9  10

In [ ]:
df2= pd.DataFrame([[1,2,3,4,5],[6,7,8,9,10]], index=list('ab'))

In [ ]:
df2

0  1  2  3   4
a  1  2  3  4   5
b  6  7  8  9  10

In [ ]:
df2= pd.DataFrame([[1,2,3,4,5],[6,7,8,9,10]],list('ze'))

In [ ]:
df2

0  1  2  3   4
z  1  2  3  4   5
e  6  7  8  9  10

In [ ]:
#df 생성시 행과 열 레이블 지정

In [ ]:
df= pd.DataFrame([[1,2,3,4,5],[6,7,8,9,10]], index=['a','b'], columns= ['a','b','c','d','e'])

In [ ]:
df

a  b  c  d   e
a  1  2  3  4   5
b  6  7  8  9  10

In [ ]:
df= pd.DataFrame([[1,2,3,4,5],[6,7,8,9,10]], index= list('ab'), columns=list('qwert'))

In [ ]:
df

q  w  e  r   t
a  1  2  3  4   5
b  6  7  8  9  10

In [ ]:
_r = list('ab')

In [ ]:
_c= list('abcde')

In [ ]:
df3= pd.DataFrame([[1,2,3,4,5],[6,7,8,9,10]], index=_r, columns=_c)

In [ ]:
df3

a  b  c  d   e
a  1  2  3  4   5
b  6  7  8  9  10

In [ ]:
#values 속성

In [ ]:
#2차원 배열로 출력

In [ ]:
df.values

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
type(df.values) #값들만 넘파이배열

numpy.ndarray

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.index

Index(['a', 'b'], dtype='object')

In [ ]:
df.columns

Index(['q', 'w', 'e', 'r', 't'], dtype='object')

In [ ]:
#차원 사이즈 형태 모델 형상

In [ ]:
df

q  w  e  r   t
a  1  2  3  4   5
b  6  7  8  9  10

In [ ]:
df.ndim

2

In [ ]:
df.size

10

In [ ]:
df.shape

(2, 5)

In [ ]:
#넘파이 함수 이용하여 df 생성

In [ ]:
#이때 reshape 로 배열의 모양을 지정

In [ ]:
df= pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]))

In [ ]:
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
df.shape

(3, 3)

In [ ]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
df1 = pd.DataFrame(np.arange(1,31).reshape(5,6))

In [ ]:
df1

0   1   2   3   4   5
0   1   2   3   4   5   6
1   7   8   9  10  11  12
2  13  14  15  16  17  18
3  19  20  21  22  23  24
4  25  26  27  28  29  30

In [ ]:
df1.values

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
df1 = pd.DataFrame(np.arange(1,31).reshape(5,6), index=list('abcde'), columns=list('abcdef'))

In [ ]:
df1

a   b   c   d   e   f
a   1   2   3   4   5   6
b   7   8   9  10  11  12
c  13  14  15  16  17  18
d  19  20  21  22  23  24
e  25  26  27  28  29  30

In [ ]:
#헷갈리는 df 색인

In [ ]:
ar =np.arange(1,31).reshape(5,6)

In [ ]:
ar[4,4]

29

In [ ]:
df = pd.DataFrame(np.arange(1,31).reshape(5,6))

In [ ]:
df

0   1   2   3   4   5
0   1   2   3   4   5   6
1   7   8   9  10  11  12
2  13  14  15  16  17  18
3  19  20  21  22  23  24
4  25  26  27  28  29  30

In [ ]:
ar[4,4]

29

In [ ]:
df[4,4]

InvalidIndexError: (4, 4)

In [ ]:
df[4][4]

29

In [ ]:
#열 기준 색인

In [ ]:
df[0]

0     1
1     7
2    13
3    19
4    25
Name: 0, dtype: int64

In [ ]:
#세로로 출력

In [ ]:
df[3][4]

28

In [ ]:
df[4][5]

KeyError: 5

In [ ]:
df[3][2]

16

#실습 3-4 Dataframe raw_data만들기, 순서 변경, 열추가, loc, iloc, fillna NaN 값 채우기

In [ ]:
#raw_data 만들기

In [ ]:
#raw_data = {}

In [ ]:
raw_data = {
    'food':['apple','pear','peach','banana','orange'],
    'month':[1,2,3,4,5],
    'quantity':[33,44,55,66,77]
}

In [ ]:
raw_data

{'food': ['apple', 'pear', 'peach', 'banana', 'orange'],
 'month': [1, 2, 3, 4, 5],
 'quantity': [33, 44, 55, 66, 77]}

In [ ]:
df=pd.DataFrame(raw_data)

In [ ]:
df

food  month  quantity
0   apple      1        33
1    pear      2        44
2   peach      3        55
3  banana      4        66
4  orange      5        77

In [ ]:
#컬럼 (열) 인덱스의 순서를 변경

In [ ]:
df

food  month  quantity
0   apple      1        33
1    pear      2        44
2   peach      3        55
3  banana      4        66
4  orange      5        77

In [ ]:
df1 = pd.DataFrame(data=raw_data, columns=['month','food','quantity'])

In [ ]:
df1

month    food  quantity
0      1   apple        33
1      2    pear        44
2      3   peach        55
3      4  banana        66
4      5  orange        77

In [ ]:
#로 (행) 인덱스 값 변경

In [ ]:
df1 = pd.DataFrame(data=raw_data,index = list('abcde'))

In [ ]:
df1

food  month  quantity
a   apple      1        33
b    pear      2        44
c   peach      3        55
d  banana      4        66
e  orange      5        77

In [ ]:
a= np.arange(5)

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
df1 = pd.DataFrame(raw_data, index = a)

In [ ]:
df1

food  month  quantity
0   apple      1        33
1    pear      2        44
2   peach      3        55
3  banana      4        66
4  orange      5        77

In [ ]:
#컬럼 순서를 변경하면서 컬럼 하나를 추가

In [ ]:
df

food  month  quantity
0   apple      1        33
1    pear      2        44
2   peach      3        55
3  banana      4        66
4  orange      5        77

In [ ]:
df1 = pd.DataFrame(data=raw_data, columns = ['quantity','month','rank','food'])

In [ ]:
df1

quantity  month rank    food
0        33      1  NaN   apple
1        44      2  NaN    pear
2        55      3  NaN   peach
3        66      4  NaN  banana
4        77      5  NaN  orange

In [ ]:
#index 행 column 열 정보 확인

In [ ]:
df1.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df1.columns

Index(['quantity', 'month', 'rank', 'food'], dtype='object')

In [ ]:
#특정한 행과 열의 값을 출력

In [ ]:
# 행 -> loc!!!!!!

In [ ]:
df1[3]

KeyError: 3

In [ ]:
df1.loc[3]   #행 출력!!!!!!!

quantity        66
month            4
rank           NaN
food        banana
Name: 3, dtype: object

In [ ]:
df1.loc[4]

quantity        77
month            5
rank           NaN
food        orange
Name: 4, dtype: object

In [ ]:
#열의 출력

In [ ]:
df1.month

0    1
1    2
2    3
3    4
4    5
Name: month, dtype: int64

In [ ]:
df1.food

0     apple
1      pear
2     peach
3    banana
4    orange
Name: food, dtype: object

In [ ]:
#loc 이용해서 원하는 행들만 출력

In [ ]:
#4행을 출력하세요?

In [ ]:
df1

quantity  month rank    food
0        33      1  NaN   apple
1        44      2  NaN    pear
2        55      3  NaN   peach
3        66      4  NaN  banana
4        77      5  NaN  orange

In [ ]:
df1.loc[1]

quantity      44
month          2
rank         NaN
food        pear
Name: 1, dtype: object

In [ ]:
df1.loc[[1,4],['quantity','food']]

quantity    food
1        44    pear
4        77  orange

In [ ]:
#Nan 부분을 빼고 출력

In [ ]:
df1

quantity  month rank    food
0        33      1  NaN   apple
1        44      2  NaN    pear
2        55      3  NaN   peach
3        66      4  NaN  banana
4        77      5  NaN  orange

In [ ]:
#작성할때 안작성하기

In [ ]:
df1.loc[[1,4]]

quantity  month rank    food
1        44      2  NaN    pear
4        77      5  NaN  orange

In [ ]:
#iloc 를 이용한 열출력

In [ ]:
df1

quantity  month rank    food
0        33      1  NaN   apple
1        44      2  NaN    pear
2        55      3  NaN   peach
3        66      4  NaN  banana
4        77      5  NaN  orange

In [ ]:
df1.month

0    1
1    2
2    3
3    4
4    5
Name: month, dtype: int64

In [ ]:
df1.iloc[:,1]  #모든행에대하여 출력을하되,

0    1
1    2
2    3
3    4
4    5
Name: month, dtype: int64

In [ ]:
df1.iloc[:,[-1]]

food
0   apple
1    pear
2   peach
3  banana
4  orange

In [ ]:
df1.iloc[:,-1:]

food
0   apple
1    pear
2   peach
3  banana
4  orange

In [ ]:
df1.iloc[:, :-1]

quantity  month rank
0        33      1  NaN
1        44      2  NaN
2        55      3  NaN
3        66      4  NaN
4        77      5  NaN

In [ ]:
#iloc 이용한 다양한출력 그냥 개헷갈림

In [ ]:
df1

quantity  month rank    food
0        33      1  NaN   apple
1        44      2  NaN    pear
2        55      3  NaN   peach
3        66      4  NaN  banana
4        77      5  NaN  orange

In [ ]:
df1.iloc[:,[0,3]]

quantity    food
0        33   apple
1        44    pear
2        55   peach
3        66  banana
4        77  orange

In [ ]:
df1.iloc[:,[0,3,1]]

quantity    food  month
0        33   apple      1
1        44    pear      2
2        55   peach      3
3        66  banana      4
4        77  orange      5

In [ ]:
df1.iloc[:, [0,1,3]]

quantity  month    food
0        33      1   apple
1        44      2    pear
2        55      3   peach
3        66      4  banana
4        77      5  orange

In [ ]:
df1

quantity  month rank    food
0        33      1  NaN   apple
1        44      2  NaN    pear
2        55      3  NaN   peach
3        66      4  NaN  banana
4        77      5  NaN  orange

In [ ]:
df1.fillna(0)

quantity  month  rank    food
0        33      1     0   apple
1        44      2     0    pear
2        55      3     0   peach
3        66      4     0  banana
4        77      5     0  orange

In [ ]:
df1

quantity  month rank    food
0        33      1  NaN   apple
1        44      2  NaN    pear
2        55      3  NaN   peach
3        66      4  NaN  banana
4        77      5  NaN  orange

In [ ]:
df2=df1.fillna(0)

In [ ]:
df1.fillna('Korea')

quantity  month   rank    food
0        33      1  Korea   apple
1        44      2  Korea    pear
2        55      3  Korea   peach
3        66      4  Korea  banana
4        77      5  Korea  orange

#실습 3-5 Dataframe true,false

In [ ]:
df1['rank']=df1.food == 'peach'

In [ ]:
df1

quantity  month   rank    food
0        33      1  False   apple
1        44      2  False    pear
2        55      3   True   peach
3        66      4  False  banana
4        77      5  False  orange

In [ ]:
df1['addcol'] =df1.food == 'peach'

In [ ]:
df1

quantity  month   rank    food  addcol
0        33      1  False   apple   False
1        44      2  False    pear   False
2        55      3   True   peach    True
3        66      4  False  banana   False
4        77      5  False  orange   False

In [ ]:
 #추가한 컬럼 삭제, 물론 원하는 열을 삭제할때도 가능

In [ ]:
del df1['addcol']

In [ ]:
df1

quantity  month   rank    food
0        33      1  False   apple
1        44      2  False    pear
2        55      3   True   peach
3        66      4  False  banana
4        77      5  False  orange

In [ ]:
#행과 열 바꾸기

In [ ]:
#Transpose

In [ ]:
df1.T

0      1      2       3       4
quantity     33     44     55      66      77
month         1      2      3       4       5
rank      False  False   True   False   False
food      apple   pear  peach  banana  orange

In [ ]:
#특정 범위만 df 생성

In [ ]:
df = pd.DataFrame(df1, index = [2,3])

In [ ]:
df

quantity  month   rank    food
2        55      3   True   peach
3        66      4  False  banana

In [ ]:
x = {
    'food':df['food'][:-1]
}

In [ ]:
pd.DatafFrame(x)

AttributeError: module 'pandas' has no attribute 'DatafFrame'

In [ ]:
data = {
    'Seoul' :{2018:1, 2019:2, 2020:1},
    'Busan' :{2018:3, 2019:1, 2020:4}
    }

In [ ]:
df4 = pd.DataFrame(data=data)

In [ ]:
df4

Seoul  Busan
2018      1      3
2019      2      1
2020      1      4

In [ ]:
x={
    'Busan':df4['Busan'][1:-1],
    'Seoul':df4['Seoul'][:-1]
}

In [ ]:
pd.DataFrame(x)

Busan  Seoul
2018    NaN      1
2019    1.0      2