<a href="https://colab.research.google.com/github/jr2950499/Numpy/blob/main/Numpy_%EC%8B%A4%EC%8A%B5_1_1%2C1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#실습 1-1

array shape type size ndim

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.25.2


In [ ]:
#numpy 이용하여 1차원 배열 만들기  (파이썬 리스트->넘파이배열)

In [ ]:
ar1 = np.array([1,2,3,4,5])

In [ ]:
ar1

array([1, 2, 3, 4, 5])

In [ ]:
print(ar1)

[1 2 3 4 5]


In [ ]:
lst = [1,2,3,4,5]

In [ ]:
print(lst)

[1, 2, 3, 4, 5]


In [ ]:
print(ar1)

[1 2 3 4 5]


In [ ]:
#배열의 모양을 알 수있

In [ ]:
ar1

array([1, 2, 3, 4, 5])

In [ ]:
ar1.shape

(5,)

In [ ]:
ar1 = ['a','b','c']

In [ ]:
ar1.shape

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
ar1 = np.array(['a','b','c'])

In [ ]:
ar1

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
print(ar1)

['a' 'b' 'c']


In [ ]:
ar1.shape

(3,)

In [ ]:
lst=[1,2,3,4,5]

In [ ]:
lst

[1, 2, 3, 4, 5]

In [ ]:
ar2 = np.array(lst)

In [ ]:
ar2

array([1, 2, 3, 4, 5])

In [ ]:
print(ar2)

[1 2 3 4 5]


In [ ]:
ar2.shape

(5,)

In [ ]:
#shape 모양,형태,몸매,체형

In [ ]:
arr1 = np.array([1,2,3])

In [ ]:
arr1

array([1, 2, 3])

In [ ]:
arr1.shape

(3,)

In [ ]:
#넘파이 다차원 배열

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [ ]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1.size

6

In [ ]:
#3x4

In [ ]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#3x3

In [ ]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#type check

In [ ]:
arr =[1,2,3,4,5]

In [ ]:
arr

[1, 2, 3, 4, 5]

In [ ]:
type(arr)

list

In [ ]:
ndarr=np.array(arr)

In [ ]:
ndarr

array([1, 2, 3, 4, 5])

In [ ]:
print(ndarr)

[1 2 3 4 5]


In [ ]:
type(arr)

list

In [ ]:
type(ndarr)

numpy.ndarray

In [ ]:
ndarr

array([1, 2, 3, 4, 5])

In [ ]:
ndarr.shape

(5,)

In [ ]:
arr   #파이썬 리스트는 shape 사용불가

[1, 2, 3, 4, 5]

In [ ]:
arr1.size

6

In [ ]:
arr2.size

12

In [ ]:
arr3.size

9

In [ ]:
arr4 = np.array([[1,2,3,],[7,8,9],['a','b','c']])

In [ ]:
print(arr4)

[['1' '2' '3']
 ['7' '8' '9']
 ['a' 'b' 'c']]


In [ ]:
arr4.shape

(3, 3)

In [ ]:
arr4.size

9

In [ ]:
print(arr4)  #3차원 아니라 2차원이다 3차원은 3x2x2이런형식

[['1' '2' '3']
 ['7' '8' '9']
 ['a' 'b' 'c']]


In [ ]:
#차원 아는 것 .ndim

In [ ]:
arr4.ndim

2

In [ ]:
arr1.ndim

2

#실습 1-2

size len 차이  (len 은 큰방이 한 요소)
shape identicaltype

In [ ]:
#size->몇개의 요소가 들어있는지를 반환!
#len->중첩된 리스트의 경우 바깥리스트를 기준으로 몇개의 요소가 들어있는지 체크하면 이해가 쉽다.
#넘파이 요소는 모두 동일한 타입 그래서 파이썬 리스트 보다 빠르다

In [ ]:
#size vs len

In [ ]:
a= np.array(['a','b','c'])

In [ ]:
a

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
a.size

3

In [ ]:
len(a)

3

In [ ]:
ndarr = np.array([['a','b','c'],['d','e','f']])

In [ ]:
print(ndarr)

[['a' 'b' 'c']
 ['d' 'e' 'f']]


In [ ]:
ndarr.shape

(2, 3)

In [ ]:
ndarr.size

6

In [ ]:
len(ndarr)

2

In [ ]:
#3X4 구조

In [ ]:
lst = [['a','b','c','d'],['e','f','g','h'],['i','j','k','l']]

In [ ]:
print(lst)

[['a', 'b', 'c', 'd'], ['e', 'f', 'g', 'h'], ['i', 'j', 'k', 'l']]


In [ ]:
ndarr = np.array(lst)

In [ ]:
ndarr

array([['a', 'b', 'c', 'd'],
       ['e', 'f', 'g', 'h'],
       ['i', 'j', 'k', 'l']], dtype='<U1')

In [ ]:
print(ndarr)

[['a' 'b' 'c' 'd']
 ['e' 'f' 'g' 'h']
 ['i' 'j' 'k' 'l']]


In [ ]:
ndarr.shape

(3, 4)

In [ ]:
ndarr.size

12

In [ ]:
len(ndarr)

3

In [ ]:
len(ndarr[0])

4

In [ ]:
len(ndarr[1])

4

In [ ]:
len(ndarr[2])

4

In [ ]:
#shape

In [ ]:
test1 = np.array([[1,2],[3,4]])

In [ ]:
test1

array([[1, 2],
       [3, 4]])

In [ ]:
test1.shape

(2, 2)

In [ ]:
#identical type

In [ ]:
lst=[1,2,3,'a','b','c']

In [ ]:
lst

[1, 2, 3, 'a', 'b', 'c']

In [ ]:
lst[0]

1

In [ ]:
type(lst[0])

int

In [ ]:
ndarr = np.array(lst)

In [ ]:
print(ndarr)   #모두 동일한 타입을 만든것이다

['1' '2' '3' 'a' 'b' 'c']


In [ ]:
type(ndarr[0])

numpy.str_