<a href="https://colab.research.google.com/github/jr2950499/Numpy/blob/main/Numpy_%EC%8B%A4%EC%8A%B5_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 실습 2-1 인덱싱

In [ ]:
#기본인덱싱

In [ ]:
import numpy as np

In [ ]:
ar = np.arange(10)

In [ ]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar [4:7]

array([4, 5, 6])

In [ ]:
#범위를 지정한 요소들의 값을 한번에 변경

In [ ]:
ar [4:7] = 0

In [ ]:
ar[:]

array([0, 1, 2, 3, 0, 0, 0, 7, 8, 9])

In [ ]:
ar

array([0, 1, 2, 3, 0, 0, 0, 7, 8, 9])

In [ ]:
#2차원 배열

In [ ]:
arar = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arar.shape

(3, 3)

In [ ]:
ar25size = np.arange(1,26).reshape(5,5)

In [ ]:
ar25size

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#3행만 출력하세요

In [ ]:
ar25size[3]

array([16, 17, 18, 19, 20])

In [ ]:
ar25size[3,]

array([16, 17, 18, 19, 20])

In [ ]:
#24를 출력하세요

In [ ]:
ar25size[4,3]

24

In [ ]:
#17,18,19를 출력

In [ ]:
ar25size[3,1:4]

array([17, 18, 19])

In [ ]:
ar25size[4,1:3]

array([22, 23])

In [ ]:
ar25size[-1,1:3]

array([22, 23])

In [ ]:
#2행,3행만 출력하시오

In [ ]:
ar25size[2:3]

array([[11, 12, 13, 14, 15]])

In [ ]:
ar25size[2:3].ndim

2

In [ ]:
ar25size[2:4]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
ar25size[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
ar25size[4]

array([21, 22, 23, 24, 25])

In [ ]:
ar25size[-1]

array([21, 22, 23, 24, 25])

In [ ]:
#역 인덱스

In [ ]:
ar25size[-2]

array([16, 17, 18, 19, 20])

#실습 2-2 인덱싱 열 기준 색인

In [ ]:
#열기준으로 인덱싱

In [ ]:
ar25size = np.arange(1,26).reshape(5,5)

In [ ]:
ar25size

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
ar25size[ : ,2]

array([ 3,  8, 13, 18, 23])

In [ ]:
ar25size[, 2]

SyntaxError: invalid syntax (<ipython-input-46-4baaf9cc0dfc>, line 1)

In [ ]:
ar25size[:,4]

array([ 5, 10, 15, 20, 25])

In [ ]:
ar25size[:,-1]

array([ 5, 10, 15, 20, 25])

In [ ]:
#3미만인 열의 인덱스 값을 출력?

In [ ]:
ar25size[:,:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [ ]:
ar25size[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [ ]:
ar25size[:,1:-1]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [ ]:
ar25size[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [ ]:
#2,3,4,7,8,9 값을 0으로 채울게

In [ ]:
ar25size[:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [ ]:
ar25size[:2,1:4] = 0

In [ ]:
ar25size

array([[ 1,  0,  0,  0,  5],
       [ 6,  0,  0,  0, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#실습 2-3 뷰,고유 인덱싱방식

In [ ]:
#[][]방법으로 확인

In [ ]:
ar30size = np.arange(1,31).reshape(5,6)

In [ ]:
ar30size

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
ar30size[0]

array([1, 2, 3, 4, 5, 6])

In [ ]:
ar30size[2]

array([13, 14, 15, 16, 17, 18])

In [ ]:
ar30size[-1]

array([25, 26, 27, 28, 29, 30])

In [ ]:
ar30size[4,4]

29

In [ ]:
ar30size[4][4]

29

In [ ]:
type(ar30size)

numpy.ndarray

In [ ]:
ar30size[1][1:]

array([ 8,  9, 10, 11, 12])

In [ ]:
ar30size[-1][2:5]

array([27, 28, 29])

In [ ]:
#a변수에 담아서 값을 변경해보시오

In [ ]:
a=ar30size[-1][2:5]

In [ ]:
a

array([27, 28, 29])

In [ ]:
a[-1]=0

In [ ]:
a

array([27, 28,  0])

In [ ]:
ar30size

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28,  0, 30]])

In [ ]:
#원본도 0으로 바뀐다

In [ ]:
ar30size

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28,  0, 30]])

In [ ]:
ar30size[1,1:]

array([ 8,  9, 10, 11, 12])

In [ ]:
#넘파이만의 고유 인덱싱 방식

In [ ]:
#파이썬 중첩리스트와 비교

In [ ]:
lst = [[1,2,3,4,5],[6,7,8,9,10]]

In [ ]:
type(lst)

list

In [ ]:
lst[1][-1]

10

In [ ]:
lst[1,-1]  #오류뜸

TypeError: list indices must be integers or slices, not tuple

In [ ]:
lst1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
lst1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
type(lst1)

numpy.ndarray

In [ ]:
lst1[1,-1]

10

In [ ]:
lst[1][-1]

10

#실습 2-4 짝수(홀수)행출력

In [ ]:
#짝수행만 출력

In [ ]:
ar30size = np.arange(1,31).reshape(5,6)

In [ ]:
ar30size[:2,1:4]

array([[ 2,  3,  4],
       [ 8,  9, 10]])

In [ ]:
#for문

In [ ]:
for i in range(5):
    if i%2 ==0:
        print(i)

0
2
4


In [ ]:
for i in range(5):
    if i%2 ==0:
        print(ar30size[i])

[1 2 3 4 5 6]
[13 14 15 16 17 18]
[25 26 27 28 29 30]


In [ ]:
ar30size.shape

(5, 6)

In [ ]:
ar30size.shape[0]

5

In [ ]:
for i in range(ar30size.shape[0]):
    if i%2 ==0:
        print(ar30size[i])

[1 2 3 4 5 6]
[13 14 15 16 17 18]
[25 26 27 28 29 30]


In [ ]:
#짝수열만 출력

In [ ]:
for i in range(5):
    for j in range(6):
        if j%2 == 0:
            print(ar30size[i][j])

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29


In [ ]:
for i in range(ar30size.shape[0]):
    for j in range(ar30size.shape[1]):
        if j%2 == 0:
            print(ar30size[i][j], end=' ')
    print()

1 3 5 
7 9 11 
13 15 17 
19 21 23 
25 27 29 


In [ ]:
for i in range(ar30size.shape[0]):
    for j in range(ar30size.shape[1]):
        if j%2 == 0:
            print(ar30size[i][j], end='\t')
    print()

1	3	5	
7	9	11	
13	15	17	
19	21	23	
25	27	29	


In [ ]:
#\t ,\n 차이?

In [ ]:
#for문 사용하지않고 넘파이 고유방식

In [ ]:
ar30size

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
ar30size[::2]

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
ar30size[::3]

array([[ 1,  2,  3,  4,  5,  6],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
ar30size[:3:3]

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
ar30size[1: :2]

array([[ 7,  8,  9, 10, 11, 12],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
ar30size[-1: :1]

array([[25, 26, 27, 28, 29, 30]])

In [ ]:
ar30size[-1: : -1]

array([[25, 26, 27, 28, 29, 30],
       [19, 20, 21, 22, 23, 24],
       [13, 14, 15, 16, 17, 18],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6]])

#실습 2-5 broadcasting

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a=a.reshape(3,3)

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
b= np.array([1,2,3])

In [ ]:
b

array([1, 2, 3])

In [ ]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [ ]:
b=np.array([[1],[2],[3]])

In [ ]:
b

array([[1],
       [2],
       [3]])

In [ ]:
b.shape

(3, 1)

In [ ]:
a+b

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [ ]:
a=np.array([[1],[2],[3]])

In [ ]:
a

array([[1],
       [2],
       [3]])

In [ ]:
b=np.array([1,2,3])

In [ ]:
b

array([1, 2, 3])

In [ ]:
a+b

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
a=np.array([1,2,3])

In [ ]:
b=np.array([[1],[2],[3]])

In [ ]:
a+b

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
a= np.arange(1,10).reshape(3,3)

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.shape

(3, 3)

In [ ]:
b=np.array([1,2])

In [ ]:
a+b

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

#실습 2-6 broadcasting 연습문제, 비교연산

In [ ]:
#문제 아래의 배열 a,b,c 각각형상 말하기, a+b, a+c 연산 가능한지, 그 결과 나오는 배열은 무슨 형상인지

In [ ]:
a= np.array([[1],[2],[3],[4],[5],[6]])

In [ ]:
b=np.array([1,2,3])

In [ ]:
c=np.array([[1,2,3]])

In [ ]:
#001각각의 형상은?

In [ ]:
a.shape

(6, 1)

In [ ]:
b.shape

(3,)

In [ ]:
c.shape

(1, 3)

In [ ]:
#a+b 가능?

In [ ]:
a+b  #차원이달라도 연산 수행가능

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [ ]:
a+c

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [ ]:
(a+b).shape

(6, 3)

In [ ]:
#문제 아래의 배열들에 대하여 각각의 요소 값을 비교해보시오?

In [ ]:
a= np.array([[1,2,3],[4,5,6]])

In [ ]:
b=np.array([[7,8,3],[1,5,2]])

In [ ]:
c=np.array([7,8,9])

In [ ]:
d=np.array([7,8])

In [ ]:
e=np.array([1,2,3,4])

In [ ]:
#여기서는 == 비교했을때 결과값과 != 비교했을때의 결과 값을 잘 기억하는게 중요하다

In [ ]:
a==b

array([[False, False,  True],
       [False,  True, False]])

array([False, False, False])

In [ ]:
#a,d,e 는 broadcasting 이 안되고, 비교연산조차안됨

In [ ]:
a+d

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U39'), dtype('int64')) -> None

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b

array([[7, 8, 3],
       [1, 5, 2]])

In [ ]:
a+b

array([[ 8, 10,  6],
       [ 5, 10,  8]])

In [ ]:
print(a==b)

[[False False  True]
 [False  True False]]


In [ ]:
a+c

array([[ 8, 10, 12],
       [11, 13, 15]])

In [ ]:
a==c

array([[False, False, False],
       [False, False, False]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b

array([[7, 8, 3],
       [1, 5, 2]])

In [ ]:
a!=b #같지않냐고 물어보는거임 (반대로)

array([[ True,  True, False],
       [ True, False,  True]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b

array([[7, 8, 3],
       [1, 5, 2]])

In [ ]:
a==b

array([[False, False,  True],
       [False,  True, False]])

In [ ]:
a>b

array([[False, False, False],
       [ True, False,  True]])

In [ ]:
a>c

array([[False, False, False],
       [False, False, False]])

#실습 2-7 indexing slicing 연습문제

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
a[5:-1]

array([6, 7, 8])

In [ ]:
a = np.arange(1,10).reshape(3,3)

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[0]

array([1, 2, 3])

In [ ]:
a[1]

array([4, 5, 6])

In [ ]:
a[0][1]

2

In [ ]:
a[0:-1]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[-1]

array([7, 8, 9])

In [ ]:
a[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
a[:1,:2]

array([[1, 2]])

In [ ]:
a[1:2,1:2]

array([[5]])

In [ ]:
a = np.arange(1,26).reshape(5,5)

In [ ]:
a[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

In [ ]:
a[:3,1:3]

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

In [ ]:
a[0:3][1:3]  #이미 이루어진거에거 2차 인덱싱된거임

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
a[2:][:2]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
a[3:5,2:4]

array([[18, 19],
       [23, 24]])

In [ ]:
#문제

In [ ]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#8값이 나오도록 인덱싱

In [ ]:
a[2,1]

8

In [ ]:
#4,5,6값이 나오도록 슬라이싱

In [ ]:
a[1]

array([4, 5, 6])

In [ ]:
a[1:2]

array([[4, 5, 6]])

In [ ]:
#1,2,3,4,5,6 나오도록 슬라이싱, 다중슬라이싱

In [ ]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [ ]:
#4,5,7,8, 나오도록 다중슬라이싱

In [ ]:
a[1:3, :2]

array([[4, 5],
       [7, 8]])

#실습 2-8 view vs copy

In [ ]:
#인덱싱, 슬라이싱 한후에 나온배열 -> 뷰 (원본훼손)

In [ ]:
#그래서 copy 사용

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1=a[:5]

In [ ]:
a1

array([1, 2, 3, 4, 5])

In [ ]:
a1[:5]=100

In [ ]:
a1

array([100, 100, 100, 100, 100])

In [ ]:
a #원본훼손

array([100, 100, 100, 100, 100,   6,   7,   8,   9])

In [ ]:
b= np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b1=b[:5].copy()

In [ ]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b1  #엥 이거 왜 안돼!

array([1, 2, 3, 4, 5])

In [ ]:
c= np.arange(1,26).reshape(5,5)

In [ ]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
c1 = c[-1].copy()

In [ ]:
c1[:]=400

In [ ]:
c1

array([400, 400, 400, 400, 400])

In [ ]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#실습 2-9 3d array

In [ ]:
#3차원 배열 생성

In [ ]:
a=np.arange(24).reshape(2,3,4)

In [ ]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a.shape

(2, 3, 4)

In [ ]:
a.ndim

3

In [ ]:
a.size

24

In [ ]:
b=np.arange(24).reshape(2,4,3)

In [ ]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [ ]:
a = np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]])

In [ ]:
a

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [ ]:
a.ndim

3

In [ ]:
a.shape

(2, 3, 3)

In [ ]:
a.size

18

In [ ]:
a[0]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
a = np.arange(27).reshape(3,3,3)

In [ ]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a[0,2]

array([6, 7, 8])

In [ ]:
a[0,2,-1]

8

In [ ]:
a[-1,-1,:2]

array([24, 25])

In [ ]:
a=np.arange(1,51).reshape(2,5,5)

In [ ]:
a

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]],

       [[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50]]])

In [ ]:
a[1,2:,1:4]

array([[37, 38, 39],
       [42, 43, 44],
       [47, 48, 49]])

#실습 2-10 2,3차원배열, 2중3중 for문, append 메서드